# Generated by Django 3.1.4 on 2020-12-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201218_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='passowrd',
            field=models.CharField(max_length=500),
        ),
    ]
