# Generated by Django 3.1.4 on 2020-12-18 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201218_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='passowrd',
            new_name='password',
        ),
    ]
