# Generated by Django 3.1.4 on 2020-12-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201223_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='statul',
            field=models.BooleanField(default=False),
        ),
    ]
