# Generated by Django 3.1.4 on 2020-12-23 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_statul'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='statul',
            new_name='status',
        ),
    ]
